name: Deploy and Build on RHEL server

on:
  push:
    branches:
      - master

jobs:
  deploy_and_build:
    name: Deploy and Build on RHEL server
    runs-on: ubuntu-latest
    env:
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{  secrets.SSH_USERNAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "*"
        target: /home/$SSH_USER/NumberToWords
        
    #- name: Copy repository to RHEL server
      #run: |
        #echo "$SSH_KEY" > private_key
        #chmod 400 private_key
       # sudo scp -o StrictHostKeyChecking=no -i private_key -r ./* $SSH_USER@${{ secrets.SSH_HOST }}:/home/$SSH_USER/NumberToWords

        

        

    - name: Execute build on RHEL server

      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USERNAME }}/NumberToWords
          # Execute build commands for NumberToWords
          dotnet build &
          # dotnet publish --configuration Release --output ./publish

          cd /home/${{ secrets.SSH_USERNAME }}/NumberToWordsTest
          # Execute build commands for Project2
          dotnet build &
          #dotnet publish --configuration Release --output ./publish
          

          cd /home/${{ secrets.SSH_USERNAME }}/NumberToWordsTestByConsole
          # Execute build commands for Project3
          dotnet build &
          #dotnet publish --configuration Release --output ./publish

          cd /home/${{ secrets.SSH_USERNAME }}/NumberToWordsTestByReact
          # Execute build commands for Project4
          npm install &
          npm start &
          
    - name: Clean up private_key
      if: success()

      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd NumberToWords
          rm private_key

    - name: Clean up on failure
      if: failure()

      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd NumberToWords
          rm -rf *
