name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project-folder: [ 'NumberToWords', 'NumberToWordsTest', 'NumberToWordsTestByConsole' ]

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Display system information
      run: |
        dotnet --info
        echo "Building project at ${{ matrix.project-folder }}"

    - name: Build .NET project
      working-directory: ${{ matrix.project-folder }}
      run: |
        dotnet restore
        dotnet build --configuration Release
        dotnet publish --configuration Release --output ./publish

    - name: Upload build output to server
      run: |
        echo "Deploying project from ${{ matrix.project-folder }}/publish to $SSH_HOST"
        scp -o StrictHostKeyChecking=no -i $SSH_KEY -r ${{ matrix.project-folder }}/publish/* $SSH_USERNAME@$SSH_HOST:/path/to/deploy/${{ matrix.project-folder }}

    - name: Restart Service
      run: |
        echo "Restarting service on $SSH_HOST"
        ssh -o StrictHostKeyChecking=no -i $SSH_KEY $SSH_USERNAME@$SSH_HOST 'sudo systemctl restart your_service_name'

  build-react:
    runs-on: ubuntu-latest
    needs: build-dotnet

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Display Node.js information
      run: |
        node --version
        npm --version
        echo "Building React project"

    - name: Build React project
      working-directory: project4
      run: |
        npm install
        npm run build

    - name: Upload React build output to server
      run: |
        echo "Deploying React build output to $SSH_HOST"
        scp -o StrictHostKeyChecking=no -i $SSH_KEY -r NumberToWordsTestByReact/build/* $SSH_USERNAME@$SSH_HOST:/path/to/deploy/project4
