name: Deploy and Build on RHEL server

on:
  push:
    branches:
      - master

jobs:
  deploy_and_build:
    name: Deploy and Build on RHEL server
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{  secrets.SSH_USERNAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Creating project folder
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf NumberToWords
          mkdir NumberToWords
    - name: Copy repository to RHEL server
      run: |
        echo "$SSH_KEY" > private_key
        chmod 400 private_key
        sudo scp -o StrictHostKeyChecking=no -i private_key -r ./* $SSH_USER@${{ secrets.SSH_HOST }}:/home/$SSH_USER/NumberToWords

        

        

    - name: Execute build on RHEL server

      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SSH_USERNAME }}/NumberToWords/NumberToWords
          # Execute build commands for NumberToWords
          dotnet run --configuration Release --no-restore --quiet
          dotnet publish --configuration Release --output ./publish

          cd /home/${{ secrets.SSH_USERNAME }}/NumberToWords/NumberToWordsTest
          # Execute build commands for NumberToWordsTest
          dotnet test
          dotnet publish --configuration Release --output ./publish
          

          #cd /home/${{ secrets.SSH_USERNAME }}/NumberToWords/NumberToWordsTestByConsole
          # Execute build commands for NumberToWordsTestByConsole
          #dotnet run --configuration Release --no-restore --quiet
          #dotnet publish --configuration Release --output ./publish

          cd /home/${{ secrets.SSH_USERNAME }}/NumberToWords/NumberToWordsTestByReact
          # Execute build commands for NumberToWordsTestByReact
          npm install --save-dev
          npm run start > /dev/null &
