name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Check IP
      run: curl https://api.ipify.org
    # Build Project 1 NumberToWords
    - name: Build Project1 NumberToWords
      run: |
        cd NumberToWords
        dotnet restore
        dotnet publish ./ --configuration Release --output ./out
        

    # Build Project 2 NumberToWordsTest
    - name: Build Project2 NumberToWordsTest
      run: |
        cd NumberToWordsTest
        dotnet test &
        dotnet publish ./ --configuration Release --output ./out

    # Build Project 3 NumberToWordsTestByConsole
    - name: Build & deploy Project3 NumberToWordsTestByConsole
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        cd NumberToWordsTestByConsole 
        dotnet restore
        dotnet publish ./ --configuration Release --output ./out
        ls


    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 107.20.103.164
        username: root
        port: 22
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "./NumberToWordsTestByConsole/out/*"
        target: /
          #sudo scp -i private_key -r -o StrictHostKeyChecking=no out/* ec2@107.20.103.164:/
       
    # Build Project 4 NumberToWordsTestByReact
    - name: Build Project4 NumberToWordsTestByReact
      run: |
        cd NumberToWordsTestByReact
        npm install &
        npm start &
        ls
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Prepare SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy repo1
      run: |
        cd NumberToWordsTestByConsole
        ls
      # scp -r -o StrictHostKeyChecking=no ./NumberToWordsTest/NumberToWordsTestByConsole/out/* centos@107.20.103.164:${{ env.DEPLOY_PATH }}/

      



        

    - name: Notify on failure
      if: failure()
      run: echo "Deployment failed!"
